Repository MaeumGaGym/MaeumGaGym_Flutter, pull requests merged in 2024-03, with the labels that each got.

#378 이슈/PR 템플릿 추가
  .github/ISSUE_TEMPLATE/error.yml
  .github/ISSUE_TEMPLATE/explanation.yml
  .github/ISSUE_TEMPLATE/function.yml
  .github/ISSUE_TEMPLATE/refactoring.yml
  .github/pull_request_template.md
Labels: 문서파일추가

#382 CI Robot 세팅
  .github/pull_request_template.md
  OWNERS
Labels: kind/기능, size/M, lgtm

#381 settings for cicd
  .github/workflows/internal-deploy-play-store.yaml
  android/fastlane/Appfile
  android/fastlane/report.xml
  pubspec.yaml
  test/widget_test.dart
Labels: kind/기능, size/L, lgtm

#386 PR :: [#385] on_boarding_screen에 CircularProgressIndicator적용
  lib/core/di/login_option_di.dart
  lib/core/di/token_secure_storage_di.dart
  lib/sign_up/data/data_source/remote/google_login_remote_data_source.dart
  lib/sign_up/data/data_source/remote/kakao_login_remote_data_source.dart
  lib/sign_up/data/data_source/remote/maeumgagym_login_remote_data_source.dart
  lib/sign_up/data/data_source/remote/maeumgagym_re_issue_remote_data_source.dart
  lib/sign_up/data/repositoryImpl/google_login_repository_impl.dart
  lib/sign_up/data/repositoryImpl/kakao_login_repository_impl.dart
  lib/sign_up/domain/model/maeumgagym_login_model.dart
  lib/sign_up/domain/model/maeumgagym_re_issue_model.dart
  lib/sign_up/domain/model/social_login_model.dart
  lib/sign_up/domain/repository/social_login_repository.dart
  lib/sign_up/domain/usecase/social_login_usecase.dart
  lib/sign_up/presentation/provider/maeumgagym_login_provider.dart
  lib/sign_up/presentation/provider/maeumgagym_re_issue_provider.dart
  lib/sign_up/presentation/provider/social_login_provider.dart
  lib/sign_up/presentation/view/on_boarding_screen.dart
  lib/sign_up/presentation/widget/sign_up_nick_name/animated_check_button.dart
Labels: kind/기능, size/XL

#388 PR :: [#387] PageManagerScreen BottomNavigation 수정
  lib/page_manager/presentation/view/page_manager_screen.dart
  pubspec.yaml
Labels: kind/문서, size/XS

#389 PR :: [#376] SelfCareTextField 리팩토링
  lib/core/component/maeungagym_text_style.dart
  lib/self_care/presentation/widget/self_care_text_field.dart
Labels: kind/리펙토링, size/M, lgtm

#391 PR :: [#390] 자기관리 스크롤 버튼 리팩토링
  lib/self_care/presentation/view/goal/self_care_goal_main_screen.dart
  lib/self_care/presentation/view/my_routine/self_care_my_routine_main_screen.dart
  pubspec.yaml
Labels: kind/리펙토링, size/M, lgtm

#393 SignUp Loading Indicator 추가
  lib/sign_up/data/data_source/remote/maeumgagym_sign_up_remote_data_source.dart
  lib/sign_up/data/repositoryImpl/maeumgagym_sign_up_repository_impl.dart
  lib/sign_up/domain/model/maeumgagym_sign_up_model.dart
  lib/sign_up/domain/repository/maeumgagym_sign_up_repository.dart
  lib/sign_up/domain/usecase/maeumgagym_sign_up_usecase.dart
  lib/sign_up/presentation/provider/maeumgagym_sign_up_provider.dart
  lib/sign_up/presentation/provider/nickname_check_provider.dart
  lib/sign_up/presentation/widget/sign_up_nick_name/animated_check_button.dart
  pubspec.yaml
Labels: kind/기능, size/L
