Repository MaeumGaGym/MaeumGaGym_Flutter, pull requests merged in 2024-04, with the labels that each got.

#439 PR :: 오늘의 루틴 완료하기 및 API연동
  .github/workflows/comment-on-task.yaml
  .github/workflows/create-asana-attachment.yml
  assets/image/home_icon/clock.svg
  assets/image/home_icon/completed_circle_icon.svg
  lib/home/data/data_source/remote/home_today_routines_remote_data_source.dart
  lib/home/data/repositoryImpl/home_today_routines_repository_impl.dart
  lib/home/domain/repository/home_today_routines_repository.dart
  lib/home/domain/usecase/home_today_routines_usecase.dart
  lib/home/presentation/providers/home_today_routines_provider.dart
  lib/home/presentation/view/home_today_routine_screen.dart
  lib/home/presentation/widget/main/container/home_main_routine_container.dart
  lib/home/presentation/widget/today_routine/home_today_routine_app_bar.dart
  lib/home/presentation/widget/today_routine/home_today_routine_button.dart
  lib/home/presentation/widget/today_routine/home_today_routine_list_widget.dart
Labels: kind/기능, size/XL, approved

#440 PoseDetailScreen 오류 수정
  lib/core/component/pose/presentation/widget/tab_body/part/pose_part_widget.dart
  lib/core/component/pose/presentation/widget/tab_body/recommend/pose_recommend_widget_bottom.dart
  lib/home/presentation/widget/main/container/home_main_routine_container.dart
  lib/home/presentation/widget/today_routine/home_today_routine_list_widget.dart
  lib/pose/presentation/provider/pose_detail_provider.dart
  lib/pose/presentation/view/pose_detail_screen.dart
  lib/pose/presentation/widget/search/pose_search_body.dart
  pubspec.lock
  pubspec.yaml
Labels: size/L, approved

#441 PR :: 루틴 수정하기 API 연동
  lib/core/component/pose/presentation/widget/tab_body/part/pose_part_widget.dart
  lib/self_care/data/date_source/remote/routine_remote_data_source.dart
  lib/self_care/data/repositoryImpl/routine_repository_impl.dart
  lib/self_care/domain/model/exercise_info_edit_routine_pose_model.dart
  lib/self_care/domain/model/exercise_info_request_model.dart
  lib/self_care/domain/repository/routine_repository.dart
  lib/self_care/domain/usecase/routine_usecase.dart
  lib/self_care/presentation/provider/my_routine/self_care_my_routine_days_provider.dart
  lib/self_care/presentation/provider/my_routine/self_care_my_routine_edit_routine_provider.dart
  lib/self_care/presentation/provider/my_routine/self_care_my_routine_pose_list_provider.dart
  lib/self_care/presentation/provider/self_care_routine_item_provider.dart
  lib/self_care/presentation/view/my_routine/self_care_my_routine_add_screen.dart
  lib/self_care/presentation/view/my_routine/self_care_my_routine_detail_screen.dart
  lib/self_care/presentation/view/my_routine/self_care_my_routine_edit_screen.dart
  lib/self_care/presentation/view/my_routine/self_care_my_routine_main_screen.dart
  lib/self_care/presentation/view/my_routine/self_care_my_routine_pose_add_screen.dart
  lib/self_care/presentation/widget/my_routine/widget/self_care_my_routine_days_select_widget.dart
  lib/self_care/presentation/widget/my_routine/widget/self_care_my_routine_detail_dialog.dart
  lib/self_care/presentation/widget/my_routine/widget/self_care_my_routine_detail_title_widget.dart
  lib/self_care/presentation/widget/my_routine/widget/self_care_my_routine_item_count_widget.dart
  lib/self_care/presentation/widget/my_routine/widget/self_care_my_routine_item_widget.dart
  lib/self_care/presentation/widget/my_routine/widget/self_care_my_routine_manage_bottom_sheet.dart
  lib/self_care/presentation/widget/my_routine/widget/self_care_my_routine_pose_item_widget.dart
  lib/self_care/presentation/widget/self_care_text_field.dart
  pubspec.yaml
Labels: kind/기능, lgtm, size/XL, approved

#443 PR :: 루틴 제거 API 연동
  lib/self_care/data/date_source/remote/routine_remote_data_source.dart
  lib/self_care/data/repositoryImpl/routine_repository_impl.dart
  lib/self_care/domain/repository/routine_repository.dart
  lib/self_care/domain/usecase/routine_usecase.dart
  lib/self_care/presentation/provider/my_routine/self_care_my_routine_delete_routine_provider.dart
  lib/self_care/presentation/view/my_routine/self_care_my_routine_detail_screen.dart
  lib/self_care/presentation/widget/my_routine/widget/self_care_my_routine_manage_bottom_sheet.dart
  pubspec.yaml
Labels: size/L, lgtm, approved

#447 PR :: 타이머 로직 수정, 이미지 캐싱
  lib/core/component/image_widget.dart
  lib/home/presentation/providers/timer_state_provider.dart
  lib/home/presentation/widget/timer/container/home_timer_func_button_list_container.dart
  lib/home/presentation/widget/timer/widget/home_timer_cupertino_picker_widget.dart
  lib/home/presentation/widget/timer/widget/home_timer_time_picker_widget.dart
  lib/pose/presentation/view/pose_detail_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: kind/기능, size/L, lgtm, approved

#448 PR :: :flutter video player not initialized 없애기
  lib/core/component/pose/presentation/widget/tab_body/part/pose_part_widget.dart
  lib/core/component/pose/presentation/widget/tab_body/recommend/pose_recommend_widget_bottom.dart
  lib/home/presentation/widget/main/container/home_main_routine_container.dart
  lib/home/presentation/widget/today_routine/home_today_routine_list_widget.dart
  lib/pose/presentation/provider/pose_detail_provider.dart
  lib/pose/presentation/view/pose_detail_screen.dart
  lib/pose/presentation/widget/search/pose_search_body.dart
  pubspec.yaml
Labels: size/L, lgtm, approved

#449 PR :: 타이머 추가적인 기능 구현
  assets/sounds/timer/timer_end_sound.wav
  lib/home/presentation/providers/timer_state_provider.dart
  lib/home/presentation/widget/timer/widget/home_timer_time_picker_widget.dart
  pubspec.yaml
Labels: kind/기능, size/M, lgtm, approved
